### ISSUE TITLE
Feature request: Auto-refresh compositor

### ISSUE THREAD

**Issue by BeheadedKamikaze** [PidgeonTools/SuperImageDenoiser#11]
Automatically detect and refresh SID in the compositor, when changing the passes, or quality options in the panel.

Keep the `Add Super Denoiser` button, but change the text to `Refresh Super Denoiser` if one already exists.

Auto-refreshing should ignore the setting of the `Reset compositor` option. It should just update SID, never reset the whole compositor.

**Comment by DrachenSeele** [comment]
This has been implemented
