### ISSUE TITLE
Feature request: Offline compositing/denoising

### ISSUE THREAD

**Issue by BeheadedKamikaze** [PidgeonTools/SuperImageDenoiser#12]
Add an option to render the passes direct to OpenEXR and skip compositing. In a separate step, load the OpenEXR and perform denoising and other compositing.

This will allow people with heavy scenes or low RAM to work around having failed (black) passes due to out-of-memory conditions.

## Step 1/Mode 1: Render
Should disable the Compositor, and set the Output Format to Multi-Layer OpenEXR. This will automatically save every render layer to the output image. It will also work if they choose Render Animation.

Maybe a button to restore the user's selected Output Format and re-enable the Compositor if they want to turn it off.

## Step 2/Mode 2: Denoising/Compositing
Should either import the image, or connect up a selected `Image` compositor node to the *Super Image Denoiser* (or add one), ready for compositing and denoising when the user renders.

Could use an `Image Sequence` if they rendered an animation.

**Comment by DrachenSeele** [comment]
This is already a feature in blender itself and has already been implemented in the beta branch.
