### ISSUE TITLE
Hi, I found an stupid flaw on gumroad with your SID addon.

### ISSUE THREAD

**Issue by nurb2kea** [PidgeonTools/SuperImageDenoiser#15]
![Screenshot 2023-06-02 at 11 59 53 pm](https://github.com/PidgeonTools/SuperImageDenoiser/assets/57676085/4d67a99b-931d-450e-8ed7-3a2252331857)

**Comment by DrachenSeele** [comment]
Hi,
That is indeed a stupid bug.
But it's nothing to do with SID, that's something with gumroad.

What did the gumroad support say about this?

Kind regards,
Kevin Lorengel



nurb2kea ***@***.***> schrieb am Sa., 3. Juni 2023, 00:09:

**Comment by DrachenSeele** [comment]
Since this is an issue purely with gumroad, and nothing to do with SID, I will close this issue.

I gave it a 90% discount and I don't know why gumroad gives me the option to do so, if it is apparently not possible after all.

**Comment by nurb2kea** [comment]
Yeah, I know it's gumroad. I just wanted to let you know.
And after no e-mail address of you and discord only accept me with a mobile number, I have choosen this way!!

**Comment by DrachenSeele** [comment]
Thank you for letting me know!
I most certainly did not expect that to be an issue.

You can download the beta version for free on this github repository. It's
the "sid-temporal" branch

nurb2kea ***@***.***> schrieb am Sa., 3. Juni 2023, 00:32:

**Comment by nurb2kea** [comment]
Not my day. LOL

![Screenshot 2023-06-03 at 12 53 22 am](https://github.com/PidgeonTools/SuperImageDenoiser/assets/57676085/9e270c6d-bbb2-4595-aedc-a1f5fe9c91a2)

**Comment by DrachenSeele** [comment]
That's because you aren't subscribed, I closed the issue, so it stopped
that subscription.
Or so I think.

BTW, what's your discord name? I can give you the member role, bypassing
the phone verification requirement.

If you want to join, ofc.



nurb2kea ***@***.***> schrieb am Sa., 3. Juni 2023, 00:54:

**Comment by nurb2kea** [comment]
That is the same as the free $0 version I already got!?

**Comment by DrachenSeele** [comment]
The free version and the beta version are not the same.

The free version quals to the Master branch.
The beta version is whatever indev branch is open at the time. Currently,
SID-temporal.

nurb2kea ***@***.***> schrieb am Sa., 3. Juni 2023, 00:59:

**Comment by nurb2kea** [comment]
Ok!

discord name is usually nurb2kea too
 thx
